### ISSUE TITLE
R40 User authentication running sudo

### ISSUE THREAD

**Issue by obp-anssi** [yuumasato/scap-security-guide#14]
I think the wrong recommendation got removed. The recommendation "User authentication running sudo" was removed from the final version of the guide and the recommendation R40 "Using unprivileged users as target for sudo commands" is now at the index 40.

**Comment by yuumasato** [comment]
Oh, what a mistake.
So the recommendation from  version 1.2  that  should be kept and is the new R40 is the following:
```
  - id: R60
    levels:
    - intermediary
    title: Privileges of target sudo users
    description: The targeted users of a rule should be, as much as possible, non privileged users.
    status: automated
    rules:
    - sudoers_no_root_target
 ```
